name: DATA COUNTER PUBLIC UPDATE

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '30 18 * * *'   # 12:00 AM IST (6:30 PM UTC previous day)
  #   - cron: '30 22 * * *'   # 4:00 AM IST (10:30 PM UTC previous day)
  #   - cron: '30 2 * * *'    # 8:00 AM IST (2:30 AM UTC)
    # - cron: '30 6 * * *'    # 12:00 PM IST (6:30 AM UTC)
    # - cron: '30 10 * * *'   # 4:00 PM IST (10:30 AM UTC)

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: NairaaOfficial/DATA
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          sparse-checkout: |
            counter_public.py
            counter_public.txt
          fetch-depth: 1

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.9'  # Specify the Python version you need

      # Install the necessary packages
      - name: Installed package list
        run: apt list --installed

      # Run your Python script
      - name: Run Python script
        run: python3 counter_public.py
        
      # Check if counter_public.txt has been modified, pull, and push the modified changes.
      - name: Commit and Push Changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add counter_public.txt
          git commit -m "Update counter_public.txt after processing" || echo "No changes to commit"
          git pull --rebase origin main || echo "No changes to pull"
          git push || echo "No changes to push"
