name: INSTAGRAM STORY SCHEDULER

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '30 11 * * *'  # Runs at 5:00 PM IST
  #   - cron: '0 16 * * *'   # Runs at 9:30 PM IST
  
jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: NairaaOfficial/SOCIAL_MEDIA
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          sparse-checkout: |
            STORY_TO_UPLOAD/
            INSTAGRAM/
            counter_video.txt
            requirements.txt
          fetch-depth: 1

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.9'

      # Install the necessary packages
      - name: Installed package list
        run: apt list --installed
      
      # Read the counter_video value and set sparse-checkout for the specific video
      - name: Download Video
        run: |
          VIDEO_NUMBER=$(cat counter_video.txt)
          echo "Setting url checkout for url_${VIDEO_NUMBER}.mp4"
          curl -o "STORY_TO_UPLOAD/story_${VIDEO_NUMBER}.mp4" "https://nairaa-babe-data.onrender.com/videos/Video_${VIDEO_NUMBER}.mp4"

      # Install dependencies
      - name: Install dependencies
        run: |
         python3 -m pip install --upgrade pip
         pip3 install -r requirements.txt

      # Run your Python script
      - name: Run Python script
        run: python3 INSTAGRAM/instagram_story.py