name: THREADS POLLS SCHEDULER

on:
  workflow_dispatch:
  # schedule:
  #    - cron: '0 */5 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: NairaaOfficial/SOCIAL_MEDIA
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}        
          sparse-checkout: |
            THREADS/
            requirements.txt
          fetch-depth: 1

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.9'

      # Install the necessary packages
      - name: Installed package list
        run: apt list --installed
        
      # Install dependencies
      - name: Install dependencies
        run: |
         python3 -m pip install --upgrade pip
         pip3 install -r requirements.txt

      # Run your Python script
      - name: Run Python script
        run: python3 THREADS/thread_polls.py